SubastandoSubastaBundle_homepage:
    pattern:  /
    defaults: { _controller: SubastandoSubastaBundle:Default:index }

SubastandoSubastaBundle_loadproduct:
    pattern:  /products
    defaults: { _controller: SubastandoSubastaBundle:Product:new }