parameters:
#    subastando_subasta.example.class: Subastando\SubastaBundle\Example

services:
#    subastando_subasta.example:
#        class: %subastando_subasta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
